TheCulture/app/main/routes.py
from flask import Blueprint, render_template

main = Blueprint("main", __name__)

@main.route('/')
@main.route("/home")
def home():
	return render_template("home.html")

@main.route("/about")
def about():
	return render_template("about.html")

TheCulture/app/reviews/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from app import db
from app.database import Review
from app.reviews.forms import ReviewForm

reviews = Blueprint("reviews", __name__)

@reviews.route("/reviews", methods = ["GET", "POST"])
def show_reviews():
	page = request.args.get("page", 1, type=int)
	reviews = Review.query.order_by(Review.date_posted.desc()).paginate(page = page, per_page = 5)
	return render_template("reviews.html", reviews = reviews)

@reviews.route("/review/<int:review_id>")
def review(review_id):
	review = Review.query.get_or_404(review_id)
	return render_template("review.html", review = review)

@reviews.route("/review/<int:review_id>/update",  methods = ["GET", "POST"])
@login_required
def update_review(review_id):
	review = Review.query.get_or_404(review_id)
	if review.author != current_user:
		abort(403)
	form = ReviewForm()
	if form.validate_on_submit():
		review.title = form.title.data
		review.body = form.body.data
		db.session.commit()
		flash("Your post has been updated!", "success")
		return redirect(url_for("reviews.review", review_id = review.id))
	elif request.method == "GET":
		form.title.data = review.title
		form.body.data = review.body
	return render_template("create_review.html", legend = "Update Review", form = form)

@reviews.route("/review/<int:review_id>/delete",  methods = ["POST"])
@login_required
def delete_review(review_id):
	review = Review.query.get_or_404(review_id)
	if review.author != current_user:
		abort(403)
	db.session.delete(review)
	db.session.commit()
	flash("Your post has been deleted!", "success")
	return redirect(url_for("reviews.show_reviews"))

@reviews.route("/review/new", methods = ["GET", "POST"])
@login_required
def new_review():
	form = ReviewForm()
	if form.validate_on_submit():
		review = Review(title = form.title.data, body = form.body.data, author = current_user)
		db.session.add(review)
		db.session.commit()
		flash("Your review has been posted!", "success")
		return redirect(url_for("reviews.show_reviews"))
	return render_template("create_review.html", legend = "New Review", form = form)

@reviews.route("/latest_reviews", methods = ["GET", "POST"])
def latest_reviews():
	reviews = Review.query.order_by(Review.date_posted.desc()).paginate(page = 1, per_page = 10)
	return render_template("latest_reviews.html", reviews = reviews)

TheCulture/app/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.database import User, Review
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from app.users.utils import savePicture, sendResetEmail, id_generator


users = Blueprint("users", __name__)

@users.route("/register", methods = ["GET", "POST"])
def register():
	if current_user.is_authenticated:
		return redirect(url_for("main.home"))
	form = RegistrationForm()
	if form.validate_on_submit():
		userName = User.query.filter_by(username = form.username.data).first()
		userEmail = User.query.filter_by(email = form.email.data).first()
		if userName:
			flash("Username already exists. Please try again", "danger")
		elif userEmail:
			flash("Email already exists. Please try again", "danger")
		else:
			hashed_password = bcrypt.generate_password_hash(form.password.data)
			user = User(username = form.username.data.lower(), email = form.email.data.lower(), password = hashed_password)
			db.session.add(user)
			db.session.commit()
			flash("Your account has been created! Please sign in!", "success")
			return redirect(url_for("users.login"))
	return render_template("register.html", form = form)

@users.route("/login", methods = ["GET", "POST"])
def login():
	if current_user.is_authenticated:
		return redirect(url_for("main.home"))
	form = LoginForm()
	if form.validate_on_submit():
		userEmail = User.query.filter_by(email = form.email.data.lower()).first()
		if not userEmail:
			flash("Username does not exist. Please try again", "danger")
		elif not bcrypt.check_password_hash(userEmail.password, form.password.data):
			flash("Incorrect password. Please try again", "danger")
		else:
		 	login_user(userEmail, remember = form.remember.data)
		 	next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for("main.home"))
	return render_template("login.html", form = form)

@users.route("/reset_password", methods = ["GET", "POST"])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for("main.home"))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = user.query.filter_by(email = form.email.data).first()
		sendResetEmail(user)
		flash("An email to reset your password has been sent to your email!", "success")
		return redirect(url_for("users.login"))
	return render_template("reset_request.html", form = form)

@users.route("/reset_password/<token>", methods = ["GET", "POST"])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for("home"))
	user = user.verify_reset_token(token)
	if not user:
		flash("Token enter is invalid or has expired!", "danger")
		return redirect(url_for("users.reset_request"))
	form = ResetPasswordForm()
	if form.validate_on_submit():
			hashed_password = bcrypt.generate_password_hash(form.password.data)
			user.password = hashed_password
			db.session.commit()
			flash("Your password has been updated! Please sign in!", "success")
			return redirect(url_for("users.login"))
	return render_template("reset_token.html", form = form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for("main.home"))

@users.route("/account")
@login_required
def account():
	return render_template("account.html")

@users.route("/edit_account", methods = ["GET", "POST"])
@login_required
def edit_account():
	print current_user.image_file
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.profilePicture.data:
			newPicture = savePicture(form.profilePicture.data)
			current_user.image_file = newPicture
		current_user.username = form.username.data.lower()
		current_user.email = form.email.data.lower()
		db.session.commit()
		flash("Your account changes have been saved!", "success")
		return redirect(url_for("users.account"))
	elif request.method == "GET":
		form.username.data = current_user.username
		form.email.data = current_user.email
	return render_template("edit_account.html", form = form)

@users.route("/user/<string:username>")
def user_reviews(username):
	page = request.args.get("page", 1, type = int)
	user = User.query.filter_by(username = username).first_or_404()
	reviews = Review.query.filter_by(author = user).order_by(Review.date_posted.desc()).paginate(page = page, per_page = 5)
	return render_template("user_reviews.html", reviews = reviews, user = user)

TheCulture/app/templates/about.html
{% extends "layout.html" %}

{% block content %}
	<h1>About Me</h1>
	<p>Junior computer science major at Morehouse College. Man of Morehouse striving for greatness.
	Future software engineer as well as entrepreneur with a passion for technology and diversity.</p>
{% endblock content %}

TheCulture/app/templates/account.html
{% extends "layout.html" %}

{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{ url_for('static', filename='profilePics/' + current_user.image_file) }}">
	    <div class="media-body">
	      <h2 class="account-heading">{{ current_user.username }}</h2>
	      <p class="text-secondary">{{ current_user.email }}</p>
	    </div>
	  </div>
	  <h5>Username</h5>
	  <p class="text-secondary">{{ current_user.username }}</p>
	  <h5>Email</h5>
	  <p class="text-secondary">{{ current_user.email }}</p>
	  <a href="{{ url_for('users.edit_account') }}"><button class="btn btn-info btn-sm"><span class="fa fa-edit"></span> Edit</button></a>
	</div>
{% endblock content %}

TheCulture/app/templates/create_review.html
{% extends "layout.html" %}

{% block content %}
	<body>
	  <div class="content-section">
	    <form action="" class="form-group col-xs-3" method="POST">
	      {{ form.hidden_tag() }}
	      <fieldset class="form-group">
	        <legend class="border-bottom mb-4">{{ legend }}</legend>
	        <div class="form-group">
	          {{ form.title.label(class="form-control-label") }}
	          {% if form.title.errors %}
	            {{ form.title(class="form-control form-control-lg is-invalid") }}
	            <div class="invalid-feedback">
	              {% for error in form.title.errors %}
	                <span>{{ error }}</span>
	              {% endfor %}
	            </div>
	          {% else %}
	            {{ form.title(class="form-control form-control-lg") }}
	          {% endif %}
	        </div>
	        <div class="form-group">
	          {{ form.body.label(class="form-control-label") }}
	          {% if form.body.errors %}
	            {{ form.body(class="form-control form-control-lg is-invalid") }}
	            <div class="invalid-feedback">
	              {% for error in form.body.errors %}
	                <span>{{ error }}</span>
	              {% endfor %}
	            </div>
	          {% else %}
	            {{ form.body(class="form-control form-control-lg") }}
	          {% endif %}
	        </div>
	      </fieldset>
	      <div class="form-group">
	        {{ form.submit(class="btn btn-primary btn-sm") }}
	      </div>
	    </form>
	  </div>
	</body>
{% endblock content %}

TheCulture/app/templates/edit_account.html
{% extends "layout.html" %}

{% block content %}
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{ url_for('static', filename='profilePics/' + current_user.image_file) }}">
	    <div class="media-body">
	      <h2 class="account-heading">{{ current_user.username }}</h2>
	      <p class="text-secondary">{{ current_user.email }}</p>
	    </div>
	  </div>
	  <form action="" class="form-group col-xs-3" method="POST" enctype="multipart/form-data">
	    {{ form.hidden_tag() }}
	    <fieldset class="form-group">
	      <legend class="border-bottom mb-4">Account Information</legend>
	      <div class="form-group">
	        {{ form.username.label(class="form-control-label") }}
	        {% if form.username.errors %}
	          {{ form.username(class="form-control form-control-lg is-invalid") }}
	          <div class="invalid-feedback">
	            {% for error in form.username.errors %}
	              <span>{{ error }}</span>
	            {% endfor %}
	          </div>
	        {% else %}
	          {{ form.username(class="form-control form-control-lg") }}
	        {% endif %}
	      </div>
	      <div class="form-group">
	        {{ form.email.label(class="form-control-label") }}
	        {% if form.email.errors %}
	          {{ form.email(class="form-control form-control-lg is-invalid") }}
	          <div class="invalid-feedback">
	            {% for error in form.email.errors %}
	              <span>{{ error }}</span>
	            {% endfor %}
	          </div>
	        {% else %}
	          {{ form.email(class="form-control form-control-lg") }}
	        {% endif %}
	      </div>
	    </fieldset>
	    <div class="form-group">
	      {{ form.profilePicture.label() }}
	      {{ form.profilePicture(class="form-control-file") }}
	      {% if form.profilePicture.errors %}
	        {% for error in form.profilePicture.errors %}
	          <span class="text-danger">{{ error }}</span>
	        {% endfor %}
	      {% endif %}
	    </div><br>
	    <div class="form-group">
	      {{ form.submit(class="btn btn-primary btn-sm") }}
	    </div>
	  </form>
	</div>
{% endblock content %}

TheCulture/app/templates/home.html
{% extends "layout.html" %}

{% block content %}
	<div class="jumbotron text-center">
	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
	  <ol class="carousel-indicators">
	    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
	    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
	    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
	  </ol>
	  <div class="carousel-inner">
	    <div class="carousel-item active">
	      <img class="d-block w-100" style="width:750px;height:300px;" src="{{ url_for('static', filename='slideshowPics/woman-business-owner.jpg') }}">
	    </div>
	    <div class="carousel-item">
	      <img class="d-block w-100" style="width:750px;height:300px;" src="{{ url_for('static', filename='slideshowPics/entrepreneur-small-business.jpg') }}">
	    </div>
	    <div class="carousel-item">
	      <img class="d-block w-100" style="width:750px;height:300px;" src="{{ url_for('static', filename='slideshowPics/Black-Business-Month-800x350.jpg') }}">
	    </div>
	  </div>
	  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
	    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	    <span class="sr-only">Previous</span>
	  </a>
	  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
	    <span class="carousel-control-next-icon" aria-hidden="true"></span>
	    <span class="sr-only">Next</span>
	  </a>
	</div>
	</div>
{% endblock content %}

TheCulture/app/templates/latest_reviews.html
{% extends "layout.html" %}

{% block content %}
  <h1>Latest Reviews</h1><br>
	<ul class="list-group">
	  {% for review in reviews.items %}
		<article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profilePics/' + review.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <p class="text-muted">Posted by
                <a class="mr-2" href="{{ url_for('users.user_reviews', username = review.author.username) }}">{{ review.author.username }}</a>
                <small class="text-muted">{{ review.date_posted.strftime('%Y-%m-%d') }}</small>
              </p>
            </div>
            <h2><a class="article-title" href="{{ url_for('reviews.review', review_id = review.id) }}">{{ review.title }}</a></h2>
          </div>
        </article>
	  {% endfor %}
	</ul><br>
  <a href="{{ url_for('reviews.new_review') }}"><button class="btn btn-primary btn-sm"><span class="fa fa-edit"></span> Add Review</button></a>
{% endblock content %}

TheCulture/app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>The Culture</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
	    <div class="container">
	      <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">The Culture</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="navbar-toggler-icon"></span>
	      </button>
	      <div class="collapse navbar-collapse" id="navbarToggle">
	        <div class="navbar-nav mr-auto">
	          <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
	          <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
	          <a class="nav-item nav-link" href="{{ url_for('reviews.show_reviews') }}">Reviews</a>
	        </div>
	        <div class="navbar-nav">
	          {% if current_user.is_authenticated %}
	            <li class="dropdown show">
	              <!-- <img class="rounded-circle account-img" src="{{ image_file }}"> -->
	              <a class="nav-item nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	                {{ current_user.username }}
	              </a>
	              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
	                <br><center><a href="{{ url_for('users.account') }}"><span class="fa fa-user"></span> My Account</a><center><br>
	                <center><a href="{{ url_for('users.logout') }}"><span class="fa fa-sign-out"></span> Logout</a><center><br>
	              </div>
	            </li>
	          {% else %}
	            <a class="nav-item nav-link" href="{{ url_for('users.login') }}"><span class="fa fa-sign-in"></span> Login</a>
	            <a class="nav-item nav-link" href="{{ url_for('users.register') }}"><span class="fa fa-pencil"></span> Sign Up</a>
	          {% endif %}
	        </div>
	      </div>
	    </div>
	  </nav>
	</header>
	<main role="main" class="container">
	  <div class="row">
	    <div class="col-md-8">
		  {% with messages = get_flashed_messages(with_categories=true) %}
		    {% if messages %}
			  {% for category, message in messages %}
			    <div class="alert alert-{{ category }}" role="alert">
			      {{ message }}
			    </div>
		      {% endfor %}
		    {% endif %}
		  {% endwith %}
		  {% block content %}{% endblock content %}
	    </div>
        {% if request.path != url_for('users.register') and request.path != url_for('users.login') %}
          <div class="col-md-4">
            <div class="content-section">
              <h3>Menu</h3>
              <ul class="list-group">
              	{% if current_user.is_authenticated %}
              		<a class="list-group-item list-group-item-light" href="{{ url_for('users.user_reviews', username = current_user.username) }}">My Reviews</a>
              	{% endif %}
                <a class="list-group-item list-group-item-light" href="{{ url_for('reviews.latest_reviews') }}">Latest Reviews</a>
                <a class="list-group-item list-group-item-light" href="#">Top Reviews</a>
                <a class="list-group-item list-group-item-light" href="#">Announcements</a>
              </ul>
          	  </p>
            </div>
          </div>
        {% endif %}
      </div>
    </main>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

TheCulture/app/templates/login.html
{% extends "layout.html" %}

{% block content %}
<body>
  <div class="content-section">
    <form action="" class="form-group col-xs-3" method="POST">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Login</legend>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <div class="form-check">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary btn-sm") }}
        <small class="text-muted ml-2">
          <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
        </small><br>
      </div>
      <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
      </small>
    </form>
  </div>
</body>
{% endblock content %}

TheCulture/app/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
  <div class="content-section">
    <form action="" class="form-group col-xs-3" method="POST">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Reset Password</legend>
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-primary btn-sm") }}
      </div>
    </form>
  </div>
{% endblock content %}

TheCulture/app/templates/review.html
{% extends "layout.html" %}

{% block content %}
	<article class="media content-section">
	  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profilePics/' + review.author.image_file) }}">
	  <div class="media-body">
	    <div class="article-metadata">
	      <p class="text-muted">Posted by 
	      	<a class="mr-2" href="{{ url_for('users.user_reviews', username = review.author.username) }}">{{ review.author.username }}</a>
	      	<small class="text-muted">{{ review.date_posted.strftime('%Y-%m-%d') }}</small>
	      </p>
	    </div>
	    <h2 class="article-title">{{ review.title }}</h2>
	    <p class="article-content">{{ review.body }}</p>
	    {% if review.author == current_user %}
	      <div>
	    	<a class="btn btn-primary btn-sm m-1" href="{{ url_for('reviews.update_review', review_id=review.id) }}">Update</a>
	    	<button class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
	      </div>
	  	{% endif %}
	  </div>
	</article>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Review?</h5>
            <button class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">Are you sure you want to delete this post? This change will be final.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
            <form action="{{ url_for('reviews.delete_review', review_id=review.id) }}" method="POST">
              <input class="btn btn-danger btn-sm" type="submit" value="Delete">
        	</form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

TheCulture/app/templates/reviews.html
{% extends "layout.html" %}

{% block content %}
  <h1>Reviews</h1><br>
	<ul class="list-group">
	  {% for review in reviews.items %}
		<article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profilePics/' + review.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <p class="text-muted">Posted by
                <a class="mr-2" href="{{ url_for('users.user_reviews', username = review.author.username) }}">{{ review.author.username }}</a>
                <small class="text-muted">{{ review.date_posted.strftime('%Y-%m-%d') }}</small>
              </p>
            </div>
            <h2><a class="article-title" href="{{ url_for('reviews.review', review_id = review.id) }}">{{ review.title }}</a></h2>
          </div>
        </article>
	  {% endfor %}
	</ul>
	{% for page_num in reviews.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
	  {% if page_num %}
	    {% if reviews.page == page_num %}
	      <a class="btn btn-info mb-4" href="{{ url_for('reviews.show_reviews', page = page_num) }}">{{ page_num }}</a>
	    {% else %}
	      <a class="btn btn-outline-info mb-4" href="{{ url_for('reviews.show_reviews', page = page_num) }}">{{ page_num }}</a>
	    {% endif %}
	  {% else %}
	    ...
	  {% endif %}
	{% endfor %}<br>
  <a href="{{ url_for('reviews.new_review') }}"><button class="btn btn-primary btn-sm"><span class="fa fa-edit"></span> Add Review</button></a>
{% endblock content %}

TheCulture/app/templates/user_reviews.html
{% extends "layout.html" %}

{% block content %}
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ url_for('static', filename='profilePics/' + user.image_file) }}">
      <div class="media-body">
        <h2 class="account-heading">Reviews by {{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>
  </div>
  <ul class="list-group">
  	{% for review in reviews.items %}
  	  <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profilePics/' + review.author.image_file) }}">
        <div class="media-body">
          <div class="article-metadata">
            <p class="text-muted">Posted by
              <a class="mr-2" href="{{ url_for('users.user_reviews', username = review.author.username) }}">{{ review.author.username }}</a>
              <small class="text-muted">{{ review.date_posted.strftime('%Y-%m-%d') }}</small>
            </p>
          </div>
          <h2><a class="article-title" href="{{ url_for('reviews.review', review_id = review.id) }}">{{ review.title }}</a></h2>
        </div>
      </article>
	{% endfor %}
  </ul>
  {% for page_num in reviews.iter_pages(left_edge = 1, right_edge = 1, left_current = 1, right_current = 2) %}
	{% if page_num %}
	  {% if reviews.page == page_num %}
	    <a class="btn btn-info mb-4" href="{{ url_for('users.user_reviews', username = user.username, page = page_num) }}">{{ page_num }}</a>
	  {% else %}
	    <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_reviews', username = user.username, page = page_num) }}">{{ page_num }}</a>
	  {% endif %}
	{% else %}
	  ...
	{% endif %}
  {% endfor %}<br>
{% endblock content %}